# roles/blackbox_exporter/defaults/main.yml
blackbox_exporter_version: "0.20.0"
blackbox_exporter_prx_git: "https://github.com"
blackbox_exporter_base_url: "prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}"
blackbox_exporter_file_name: "blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz"
blackbox_exporter_url: >-
  {{ blackbox_exporter_prx_git }}/{{ blackbox_exporter_base_url }}/{{ blackbox_exporter_file_name }}
blackbox_exporter_install_dir: "/opt/blackbox_exporter"
blackbox_exporter_config_file: "/etc/blackbox_exporter/blackbox.yml"
blackbox_exporter_service_user: "blackbox_exporter"
blackbox_exporter_service_group: "blackbox_exporter"
blackbox_exporter_web_listen_address: "0.0.0.0:{{ blackbox_exporter_port }}"
blackbox_exporter_port: 9115
