---
- name: Check current elasticsearch_exporter version.
  command: "{{ elasticsearch_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: elasticsearch_exporter_version_check

- name: Download and unarchive elasticsearch_exporter into temporary location.
  unarchive:
    src: "{{ elasticsearch_exporter_download_url }}"
    dest: /tmp
    remote_src: true
  when: >
    elasticsearch_exporter_version_check.stdout is not defined
    or elasticsearch_exporter_version not in elasticsearch_exporter_version_check.stdout
  register: elasticsearch_exporter_download_check

- name: Move elasticsearch_exporter binary into place.
  copy:
    src: "/tmp/elasticsearch_exporter-{{ elasticsearch_exporter_version }}.linux-{{ elasticsearch_exporter_arch }}/elasticsearch_exporter"
    dest: "{{ elasticsearch_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart elasticsearch_exporter
  when: elasticsearch_exporter_download_check is success

- name: Create elasticsearch_exporter user.
  user:
    name: elasticsearch_exporter
    shell: /sbin/nologin
    state: present

- name: Copy the elasticsearch_exporter systemd unit file.
  template:
    src: elasticsearch_exporter.service.j2
    dest: /etc/systemd/system/elasticsearch_exporter.service
  register: elasticsearch_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart elasticsearch_exporter
  when: elasticsearch_exporter_service is changed

- name: Ensure elasticsearch_exporter is running and enabled at boot.
  service:
    name: elasticsearch_exporter
    state: "{{ elasticsearch_exporter_state }}"
    enabled: "{{ elasticsearch_exporter_enabled }}"

- name: Verify elasticsearch_exporter is responding to requests.
  uri:
    url: http://localhost:9114/
    return_content: true
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
