---
- name: Converge
  hosts: all

  vars:
    nginx_vhosts:
      - listen: "127.0.0.1:8080 default"
        server_name: "_"
        filename: "status.conf"
        extra_parameters: |
              location / {
                stub_status on;
                access_log   off;
              }

  roles:
    - role: geerlingguy.nginx
    - role: cloudweeb.nginx_exporter
