---
- name: Create nginx_exporter systemd file
  become: true
  ansible.builtin.template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
    mode: '0644'
  notify: systemctl restart nginx_exporter
