# roles/blackbox_exporter/tasks/main.yml
---
- name: Create blackbox_exporter user and group
  ansible.builtin.group:
    name: "{{ blackbox_exporter_service_group }}"
    state: present
  become: true

- name: Create blackbox_exporter user
  ansible.builtin.user:
    name: "{{ blackbox_exporter_service_user }}"
    group: "{{ blackbox_exporter_service_group }}"
    shell: /sbin/nologin
    state: present
  become: true

- name: Download blackbox_exporter
  ansible.builtin.get_url:
    url: "{{ blackbox_exporter_url }}"
    dest: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz"
    mode: '0644'
  become: true

- name: Extract blackbox_exporter
  ansible.builtin.unarchive:
    src: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ blackbox_exporter_install_dir }}"
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: "{{ blackbox_exporter_install_dir }}/blackbox_exporter"
  become: true

- name: Create blackbox_exporter configuration directory
  ansible.builtin.file:
    path: "{{ blackbox_exporter_config_file | dirname }}"
    state: directory
    owner: "{{ blackbox_exporter_service_user }}"
    group: "{{ blackbox_exporter_service_group }}"
    mode: '0755'
  become: true

- name: Copy blackbox_exporter configuration file
  ansible.builtin.template:
    src: blackbox.yml.j2
    dest: "{{ blackbox_exporter_config_file }}"
    owner: "{{ blackbox_exporter_service_user }}"
    group: "{{ blackbox_exporter_service_group }}"
    mode: '0644'
  notify: Restart blackbox_exporter
  become: true

- name: Create blackbox_exporter systemd service file
  ansible.builtin.template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd daemon and restart blackbox_exporter
  become: true

- name: Start and enable blackbox_exporter service
  ansible.builtin.systemd:
    name: blackbox_exporter
    state: started
    enabled: true
  become: true

- name: Create Consul configuration file for blackbox_exporter
  ansible.builtin.template:
    src: blackbox_exporter_consul.json.j2
    dest: /etc/consul.d/blackbox_exporter.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart Consul
  become: true
