---
# roles/packages/defaults/main.yml

node_exporter_ver: "1.7.0"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_ver }}/node_exporter-{{ node_exporter_ver }}.linux-amd64.tar.gz"
node_exporter_filename: "node_exporter-{{ node_exporter_ver }}.linux-amd64.tar.gz"
node_exporter_artifacts_dir: "/opt/node_exporter"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"

