---
# roles/packages/defaults/main.yml

packages_node_exporter_ver: "1.7.0"

packages_node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_ver }}/node_exporter"
packages_nose_exporter_url: "-{{ node_exporter_ver }}.linux-amd64.tar.g>"
packages_node_exporter_filename: "node_exporter-{{ node_exporter_ver }}.linux-amd64.tar.gz"
packages_node_exporter_artifacts_dir: "/opt/node_exporter"
packages_node_exporter_user: "node_exporter"
packages_node_exporter_group: "node_exporter"

