- name: Create node_exporter group
  ansible.builtin.group:
    name: "{{ node_exporter_group }}"
    state: present
  tags:
    - node_exporter

- name: Create node_exporter user
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    state: present
    create_home: false
  tags:
    - node_exporter

- name: Create directory for node_exporter
  ansible.builtin.file:
    path: "/opt/node_exporter"
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags:
    - node_exporter

- name: Copy node_exporter binary to correct directory
  ansible.builtin.copy:
    src: "/opt/node_exporter-{{ node_exporter_ver }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_binary }}"
    remote_src: true
    mode: '0755'
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
  tags:
    - node_exporter

- name: Configure systemd unit for node_exporter
  ansible.builtin.template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
    mode: '0644'
  tags:
    - node_exporter

- name: Restart node_exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: restarted
  tags:
    - node_exporter

# === Добавляем работу с role.json и node_exporter.json ===

- name: Read metadata from role.json
  ansible.builtin.slurp:
    src: "/etc/consul.d/role.json"
  register: role_json_raw
  tags:
    - node_exporter

- name: Parse role.json
  ansible.builtin.set_fact:
    role_meta: "{{ role_json_raw['content'] | b64decode | from_json }}"
  tags:
    - node_exporter

- name: Debug parsed roles.json
  ansible.builtin.debug:
    var: role_meta.node_meta

- name: Debug parsed role_meta
  ansible.builtin.debug:
    var: role_meta

- name: Debug role metadata
  ansible.builtin.debug:
    var: role_meta
  tags:
    - debug

- name: Generate node_exporter.json with metadata
  ansible.builtin.template:
    src: "node_exporter.json.j2"
    dest: "/etc/consul.d/node_exporter.json"
    owner: consul
    group: consul
    mode: '0644'
  tags:
    - node_exporter

- name: Restart Consul to apply changes
  ansible.builtin.systemd:
    name: consul
    state: restarted
  tags:
    - node_exporter

