---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Ensure apache_exporter is running and enabled at boot.
      service:
        name: apache_exporter
        state: started
        enabled: true

    - name: Verify apache_exporter is responding to requests.
      uri:
        url: http://localhost:9117/
        return_content: true
      register: metrics_output
      failed_when: "'Metrics' not in metrics_output.content"
